# ------------------------------------------------------------------------------
# project
# ------------------------------------------------------------------------------

[project]

name = "workspace"
version = "0.0.0"
requires-python = ">=3.14"
license = "MIT"
maintainers = [
  {name = "Andrew Young"}
]

[dependency-groups]

dev = [
    "pyright>=1.1.411",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-xdist>=3.8.0",
    "python-dotenv>=1.2.2",
    "ruff>=0.16.0",
]

# ------------------------------------------------------------------------------
# tool.uv
# ------------------------------------------------------------------------------

[tool.uv]

package = false

[tool.uv.workspace]

members = []

